#include "stubs_asm.h"

// TODO
NHSTUB(CancelHPTimer, 0x00000000)
NHSTUB(DeleteDirectory_Fut, 0x00000000)
NHSTUB(DeleteFile_Fut, 0x00000000)
NHSTUB(EngDrvRead, 0x00000000)
NHSTUB(EnterToCompensationEVF, 0x00000000)
NHSTUB(ExitFromCompensationEVF, 0x00000000)
NHSTUB(ExpCtrlTool_StartContiAE, 0x00000000)
NHSTUB(ExpCtrlTool_StopContiAE, 0x00000000)
NHSTUB(Feof_Fut, 0x00000000)
NHSTUB(Fflush_Fut, 0x00000000)
NHSTUB(GetDrive_TotalClusters, 0x00000000)
NHSTUB(GetFocusLensSubjectDistanceFromLens, 0x00000000)
NHSTUB(MoveFocusLensToDistance, 0x00000000)
NHSTUB(RenameFile_Fut, 0x00000000)
NHSTUB(Restart, 0x00000000)
NHSTUB(SetFileAttributes, 0x00000000)
NHSTUB(SetFileTimeStamp, 0x00000000)
NHSTUB(SetHPTimerAfterNow, 0x00000000)
NHSTUB(TurnOffBackLight, 0x00000000)
NHSTUB(TurnOnBackLight, 0x00000000)
NHSTUB(WriteSDCard, 0x00000000)
NHSTUB(_sqrt, 0x00000000)
NHSTUB(apex2us, 0x00000000)
NHSTUB(exmem_ualloc, 0x00000000)
NHSTUB(exmem_ufree, 0x00000000)
NHSTUB(reboot_fw_update, 0x00000000)

NHSTUB(GetLensCurrentFocalLength, 0x00000000)
NHSTUB(GetLensWideFocalLength, 0x00000000)


